# Generated by Django 5.1.1 on 2025-10-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_herocontent_updated_at_herocontent_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocontent',
            name='about',
            field=models.TextField(default='Hi'),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='status',
            field=models.TextField(default='Updated'),
        ),
    ]
