# Generated by Django 5.1.1 on 2025-10-27 19:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_herocontent_about_herocontent_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the skill or language', max_length=100)),
                ('category', models.CharField(choices=[('Programming Languages', 'Programming Languages'), ('Frontend Development', 'Frontend Development'), ('Backend Development', 'Backend Development'), ('Database', 'Database'), ('DevOps & Tools', 'DevOps & Tools'), ('Design', 'Design'), ('Other', 'Other')], max_length=50)),
                ('icon', models.CharField(default='fas fa-code', max_length=50)),
                ('proficiency', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order', '-proficiency', 'name'],
            },
        ),
    ]
