# Generated by Django 5.1.1 on 2025-11-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
